
package qlj.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceImpl", targetNamespace = "http://impl.service.qlj/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceImpl {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "helloResult", targetNamespace = "")
    @RequestWrapper(localName = "testHello", targetNamespace = "http://impl.service.qlj/", className = "qlj.service.impl.TestHello")
    @ResponseWrapper(localName = "testHelloResponse", targetNamespace = "http://impl.service.qlj/", className = "qlj.service.impl.TestHelloResponse")
    @Action(input = "http://impl.service.qlj/ServiceImpl/testHelloRequest", output = "http://impl.service.qlj/ServiceImpl/testHelloResponse")
    public String testHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
